# Generated by Django 5.1.1 on 2024-09-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
