# Generated by Django 5.1.1 on 2024-09-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='is_active',
            new_name='active',
        ),
    ]
