# Generated by Django 5.1.1 on 2024-10-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='car',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
