# Generated by Django 5.1.1 on 2024-10-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_rename_photo_car_photo1_car_photo2_car_photo3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo3',
        ),
    ]
