# Generated by Django 5.1.1 on 2024-10-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_remove_car_photo2_remove_car_photo3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='photo1',
            new_name='photo',
        ),
    ]
