# Generated by Django 5.1.1 on 2024-10-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_rename_photo_car_photo1_car_photo2_car_photo3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
