# Generated by Django 5.1.1 on 2024-10-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_car_fuel_car_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
