# Generated by Django 5.1.1 on 2024-10-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_car_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='contact',
            field=models.CharField(max_length=200),
        ),
    ]
