# Generated by Django 5.1.1 on 2024-10-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_alter_car_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='contact',
        ),
    ]
