# Generated by Django 5.1.1 on 2024-10-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_remove_car_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='contact',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
