# Generated by Django 5.1.1 on 2024-10-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_alter_car_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='contact',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
