# Generated by Django 5.1.1 on 2024-10-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_alter_car_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
