# Generated by Django 5.1.1 on 2024-10-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_alter_car_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
