# Generated by Django 5.1.1 on 2024-10-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_car_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
