# Generated by Django 5.1.1 on 2024-10-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_car_photo5_car_photo6'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
