# Generated by Django 5.1.1 on 2024-10-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_car_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='type',
            new_name='marca',
        ),
    ]
