# Generated by Django 5.1.1 on 2024-10-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0026_rename_type_car_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='exchange',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
