# Generated by Django 5.1.1 on 2024-10-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0028_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seller',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
