# Generated by Django 5.1.1 on 2024-10-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0033_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Carro'), ('moto', 'Moto')], default='car', max_length=4),
        ),
    ]
