# Generated by Django 5.1.1 on 2024-10-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0034_car_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='vehicle_type',
        ),
    ]
