# Generated by Django 5.1.1 on 2025-08-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0035_remove_car_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
