# Generated by Django 5.1.1 on 2025-08-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0036_alter_car_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='exchange',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatico', 'Automático')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(blank=True, choices=[('gasolina', 'Gasolina'), ('alcool', 'Álcool'), ('flex', 'Flex'), ('diesel', 'Diesel'), ('eletrico', 'Elétrico')], max_length=20, null=True),
        ),
    ]
