# Generated by Django 5.1.1 on 2025-08-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0037_alter_car_exchange_alter_car_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='marca',
            field=models.CharField(blank=True, choices=[('chevrolet', 'Chevrolet'), ('fiat', 'Fiat'), ('volkswagen', 'Volkswagen'), ('ford', 'Ford'), ('renault', 'Renault'), ('hyundai', 'Hyundai'), ('toyota', 'Toyota'), ('honda', 'Honda'), ('nissan', 'Nissan'), ('jeep', 'Jeep'), ('mitsubishi', 'Mitsubishi'), ('peugeot', 'Peugeot'), ('citroen', 'Citroën'), ('kia', 'Kia'), ('bmw', 'BMW'), ('mercedes', 'Mercedes-Benz'), ('audi', 'Audi'), ('volvo', 'Volvo'), ('jac', 'JAC'), ('chery', 'Chery')], max_length=50, null=True),
        ),
    ]
