# Generated by Django 5.1.1 on 2025-08-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0038_alter_car_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='exchange',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Automatico', 'Automático')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(blank=True, choices=[('Gasolina', 'Gasolina'), ('Alcool', 'Álcool'), ('Flex', 'Flex'), ('Diesel', 'Diesel'), ('Eletrico', 'Elétrico')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='marca',
            field=models.CharField(blank=True, choices=[('Chevrolet', 'Chevrolet'), ('Fiat', 'Fiat'), ('Volkswagen', 'Volkswagen'), ('Ford', 'Ford'), ('Renault', 'Renault'), ('Hyundai', 'Hyundai'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Nissan', 'Nissan'), ('Jeep', 'Jeep'), ('Mitsubishi', 'Mitsubishi'), ('Peugeot', 'Peugeot'), ('Citroen', 'Citroën'), ('Kia', 'Kia'), ('Bmw', 'BMW'), ('Mercedes', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Volvo', 'Volvo'), ('Jac', 'JAC'), ('Chery', 'Chery')], max_length=50, null=True),
        ),
    ]
