# Generated by Django 5.1.1 on 2025-08-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0039_alter_car_exchange_alter_car_fuel_alter_car_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tipo',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatch', 'Hatch'), ('pickup', 'Pickup'), ('coupé', 'Coupé'), ('convertible', 'Convertible')], max_length=20, null=True),
        ),
    ]
