# Generated by Django 5.1.1 on 2025-08-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0040_car_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinterest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='carinterest',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carinterest',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
