# Generated by Django 5.1.1 on 2025-08-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0042_car_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
