# Generated by Django 5.1.1 on 2025-08-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0043_car_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='active',
        ),
    ]
